#!/bin/bash

echo ""
echo "════════════════════════════════════════════════════════════════════════"
echo "🚀 SETUP RÁPIDO - 3 COMANDOS Y ESTÁS ONLINE"
echo "════════════════════════════════════════════════════════════════════════"
echo ""
echo "Ejecuta estos comandos en orden:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📦 PASO 1: Instalar herramientas (solo la primera vez)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   ./INSTALL_TOOLS.sh"
echo ""
echo "   (Instala Google Cloud SDK, Firebase CLI y verifica Docker)"
echo "   Tiempo: ~5 minutos"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔐 PASO 2: Autenticarte con Google"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   gcloud auth login && firebase login"
echo ""
echo "   (Se abrirán 2 ventanas del navegador para login)"
echo "   Tiempo: ~1 minuto"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎯 PASO 3: Desplegar TODO automáticamente"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   ./FIREBASE_SETUP.sh"
echo ""
echo "   Este script hará TODO sin tu intervención:"
echo "   ✓ Configurar Google Cloud"
echo "   ✓ Crear Cloud SQL (PostgreSQL)"
echo "   ✓ Construir y desplegar backend"
echo "   ✓ Configurar CI/CD desde GitHub"
echo "   ✓ Mostrar URLs finales"
echo ""
echo "   Tiempo: ~10-15 minutos"
echo ""
echo "════════════════════════════════════════════════════════════════════════"
echo ""
echo "📚 Si algo falla, consulta:"
echo "   • INSTALLATION_GUIDE.md - Instalación manual"
echo "   • FIREBASE_DEPLOYMENT.md - Deployment paso a paso"
echo "   • README.md - Documentación completa"
echo ""
echo "════════════════════════════════════════════════════════════════════════"
echo ""
